//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM04
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int ID { get; set; }
        public string City { get; set; }
        public int CountryID { get; set; }
        public int TravelTime { get; set; }
    
        public virtual Country Country { get; set; }

        public string IsEnabled
        {
            get
            {
                string enable = "True";
                if (UsersClass.GetUsers.ID == 2)
                {
                    enable = "False";
                }
                return enable;
            }
        }
    }
}
